USE HealthInsuranceClaimsDW;
GO

IF OBJECT_ID('stg.ClaimOperations', 'U') IS NULL
BEGIN
    CREATE TABLE stg.ClaimOperations (
        CLAIM_KEY VARCHAR(100) NOT NULL,
        CLAIM_ID VARCHAR(100) NOT NULL,
        CLAIM_TYPE VARCHAR(20) NOT NULL,

        BENE_ID VARCHAR(50) NOT NULL,
        POLICY_ID VARCHAR(50) NOT NULL,
        PLAN_ID VARCHAR(20) NOT NULL,
        PRIMARY_PROVIDER_ID VARCHAR(50) NOT NULL,

        CLAIM_FROM_DATE DATE NOT NULL,
        CLAIM_THRU_DATE DATE NOT NULL,
        SUBMISSION_DATE DATE NOT NULL,
        DECISION_DATE DATE NULL,
        PAYMENT_DATE DATE NULL,

        CLAIM_STATUS VARCHAR(30) NOT NULL,
        DENIAL_REASON VARCHAR(50) NULL,
        PAYMENT_STATUS VARCHAR(30) NOT NULL,

        DOCUMENTS_COMPLETE_FLAG BIT NOT NULL,
        POLICY_ACTIVE_FLAG BIT NOT NULL,
        TREATMENT_COVERED_FLAG BIT NOT NULL,
        WAITING_PERIOD_FLAG BIT NOT NULL,
        PREAUTH_REQUIRED_FLAG BIT NOT NULL,
        PREAUTH_STATUS VARCHAR(30) NOT NULL,

        BILLED_AMOUNT DECIMAL(18,2) NOT NULL,
        ELIGIBLE_AMOUNT DECIMAL(18,2) NOT NULL,
        DEDUCTIBLE_AMOUNT DECIMAL(18,2) NOT NULL,
        COPAY_AMOUNT DECIMAL(18,2) NOT NULL,
        NON_PAYABLE_AMOUNT DECIMAL(18,2) NOT NULL,
        ADJUSTMENT_AMOUNT DECIMAL(18,2) NOT NULL,
        APPROVED_AMOUNT DECIMAL(18,2) NOT NULL,
        PAID_AMOUNT DECIMAL(18,2) NOT NULL,
        SOURCE_CMS_PAYMENT_AMOUNT DECIMAL(18,2) NOT NULL,

        TURNAROUND_DAYS INT NOT NULL,
        SLA_TARGET_DAYS SMALLINT NOT NULL,
        SLA_BREACH_FLAG BIT NOT NULL,
        MANUAL_REVIEW_FLAG BIT NOT NULL,
        DUPLICATE_INDICATOR BIT NOT NULL,
        HIGH_COST_FLAG BIT NOT NULL,

        PROVIDER_RISK_SCORE DECIMAL(8,4) NOT NULL,
        FRAUD_ALERT_FLAG BIT NOT NULL,
        ESTIMATED_LEAKAGE_AMOUNT DECIMAL(18,2) NOT NULL,

        REVIEW_PRIORITY VARCHAR(20) NOT NULL,
        QUEUE_NAME VARCHAR(50) NOT NULL,
        ADJUSTER_ID VARCHAR(30) NOT NULL,

        ANALYSIS_DATE DATE NOT NULL,
        DATA_PROVENANCE VARCHAR(100) NOT NULL,

        LoadedAt DATETIME2 NOT NULL
            CONSTRAINT DF_StgClaimOperations_LoadedAt
            DEFAULT SYSUTCDATETIME()
    );
END;
GO

SELECT
    SCHEMA_NAME(schema_id) AS SchemaName,
    name AS TableName
FROM sys.tables
WHERE object_id = OBJECT_ID('stg.ClaimOperations');
GO

SELECT
    COUNT(*) AS LoadedColumns
FROM sys.columns
WHERE object_id = OBJECT_ID('stg.ClaimOperations');
GO