-- Run in the selected SQL Server or Azure SQL database.
IF SCHEMA_ID('lake') IS NULL EXEC('CREATE SCHEMA lake');
GO

IF OBJECT_ID('lake.dim_date', 'U') IS NULL
CREATE TABLE lake.dim_date (
    DATE_KEY INT PRIMARY KEY,
    FULL_DATE DATE NOT NULL UNIQUE,
    CALENDAR_YEAR INT NOT NULL,
    CALENDAR_MONTH INT NOT NULL,
    YEAR_MONTH CHAR(7) NOT NULL
);
GO

IF OBJECT_ID('lake.dim_provider', 'U') IS NULL
CREATE TABLE lake.dim_provider (
    PROVIDER_KEY VARCHAR(80) PRIMARY KEY,
    PROVIDER_ID VARCHAR(50) NULL,
    PROVIDER_ID_TYPE VARCHAR(20) NOT NULL
);
GO

IF OBJECT_ID('lake.fact_claim', 'U') IS NULL
CREATE TABLE lake.fact_claim (
    CLAIM_KEY VARCHAR(100) PRIMARY KEY,
    CLAIM_TYPE VARCHAR(20) NOT NULL,
    CLAIM_ID VARCHAR(80) NOT NULL,
    BENE_ID VARCHAR(50) NOT NULL,
    CLAIM_FROM_DATE DATE NOT NULL,
    CLAIM_THRU_DATE DATE NOT NULL,
    CLAIM_PAYMENT_AMOUNT DECIMAL(18,2) NOT NULL,
    CLAIM_TOTAL_CHARGE_AMOUNT DECIMAL(18,2) NULL,
    LINE_COUNT BIGINT NOT NULL,
    UNIQUE_PROVIDER_COUNT BIGINT NOT NULL,
    UNIQUE_PROCEDURE_COUNT BIGINT NOT NULL,
    LINE_SUBMITTED_CHARGE_AMOUNT DECIMAL(28,2) NULL,
    LINE_ALLOWED_AMOUNT DECIMAL(28,2) NULL,
    LINE_PAYMENT_AMOUNT DECIMAL(28,2) NULL,
    PRIMARY_PROVIDER_KEY VARCHAR(80) NOT NULL REFERENCES lake.dim_provider(PROVIDER_KEY),
    PRIMARY_PROVIDER_ID VARCHAR(50) NULL,
    PRIMARY_PROCEDURE_CODE VARCHAR(40) NULL,
    PRIMARY_DIAGNOSIS_CODE VARCHAR(40) NULL,
    CLAIM_YEAR INT NOT NULL,
    CLAIM_MONTH CHAR(7) NOT NULL,
    SERVICE_DAYS INT NOT NULL,
    DATE_KEY INT NOT NULL REFERENCES lake.dim_date(DATE_KEY),
    DATA_PROVENANCE VARCHAR(60) NOT NULL,
    CHECK (CLAIM_FROM_DATE <= CLAIM_THRU_DATE),
    CHECK (LINE_COUNT > 0)
);
GO

IF OBJECT_ID('lake.monthly_claims', 'U') IS NULL
CREATE TABLE lake.monthly_claims (
    CLAIM_MONTH CHAR(7) NOT NULL,
    CLAIM_TYPE VARCHAR(20) NOT NULL,
    CLAIM_COUNT BIGINT NOT NULL,
    LINE_COUNT BIGINT NOT NULL,
    CLAIM_PAYMENT_AMOUNT DECIMAL(38,2) NULL,
    CLAIM_TOTAL_CHARGE_AMOUNT DECIMAL(38,2) NULL,
    PRIMARY KEY (CLAIM_MONTH, CLAIM_TYPE)
);
GO

IF OBJECT_ID('lake.provider_claims', 'U') IS NULL
CREATE TABLE lake.provider_claims (
    PRIMARY_PROVIDER_KEY VARCHAR(80) NOT NULL,
    CLAIM_TYPE VARCHAR(20) NOT NULL,
    CLAIM_COUNT BIGINT NOT NULL,
    CLAIM_PAYMENT_AMOUNT DECIMAL(38,2) NULL,
    PRIMARY KEY (PRIMARY_PROVIDER_KEY, CLAIM_TYPE)
);
GO
